### ISSUE TITLE
Changes in ref: dev

### ISSUE THREAD

**Issue by greedyRoach** [aleksanderwozniak/table_calendar#223]
I'm currently using this in my flutter pubspec
```
table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: dev
```
Because i need to use
```
calendarController.events = events;
```
But i'm getting a lot of errors:
<img width="604" alt="Captura de Pantalla 2020-03-27 a la(s) 13 01 33" src="https://user-images.githubusercontent.com/57685250/77790903-3dbe2e80-702b-11ea-9e70-203c39359e2e.png">

It used to work fine, but then i changed my pub to:
```
table_calendar: ^2.2.3
```
To check new features (i used to have an older version of the package). Then i reverted the pubspec to:
```
table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: dev
```
Because as i said earlier i need to use:
```
calendarController.events = events;
```
but now is all messed up, what have i done ?:(

in summary, i did this:

1. I used to have an old version of the package
2. Then changed to ref:dev so i could set events in the calendarController
2. Changed pubspec to point to the most recent version of the package (2.2.3)
3. I reverted to refer to dev (ref:dev) in the pubspec again so i could set events in the calendarController
4. Now i have a bunch of errors

Have tried:
1. Flutter clean
2. Flutter package get
3. flutter pub upgrade 

but with no results
