### ISSUE TITLE
Bug? availableCalendarFormats without CalendarFormat.month 

### ISSUE THREAD

**Issue by cocacrave** [aleksanderwozniak/table_calendar#280]
Does `availableCalendarFormats` require map with `CalendarFormat.month`?
For example,
```
availableCalendarFormats: { CalendarFormat.twoWeeks: '2 weeks', CalendarFormat.week: '1 week' }
// or
availableCalendarFormats: { CalendarFormat.twoWeeks: '2 weeks' }
// or
availableCalendarFormats: { CalendarFormat.week: '1 week' }
```
throws error:
```
'package:table_calendar/src/calendar.dart': Failed assertion: line 210 pos 16:
'availableCalendarFormats.keys.contains(calendarFormat)': is not true.
```

I'm using dev channel:
```
table_calendar:
  git:
    url: git://github.com/aleksanderwozniak/table_calendar.git
    ref: dev
```

EDIT: Sorry, I found the problem.
