### ISSUE TITLE
Widget state does not persist

### ISSUE THREAD

**Issue by duzenko** [aleksanderwozniak/table_calendar#294]
I need to switch screen layouts dynamically, conditionally showing the calendar widget.
My problem is that the current month is reset to `initialSelectedDay` every time the widget shows.
I'd think that it should respect the 'CalendarController.focusedDay` field since the controller instance is reused? Is it a bug?

**Comment by agordeev** [comment]
Yes, it is. I'm experiencing the same issue. Unfortunately, the state of the widget doesn't persist. `initState()` is called when layout is updated, causing instantiating a new controller.

**Comment by aleksanderwozniak** [comment]
I've run a quick test and it does indeed reset when updating the parent widget layout. What you can do for now is use `dev` branch; assign a DateTime variable to `selectedDay` property and update it in `onDaySelected` callback.

To use `dev` branch, add this to `pubspec.yaml` file:

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: dev
```
