### ISSUE TITLE
How to change selected month with using of CalendarController ?

### ISSUE THREAD

**Issue by Frezyx** [aleksanderwozniak/table_calendar#319]
Hello! 
In my case I have right and left buttons on both sides of calendar like on header of this widget.
How i can change selected month by onTap method of this buttons?

I try to search way, and I'm found method _selectNext(), but this method is private. 

Can you help me with this, please ?

**Comment by aleksanderwozniak** [comment]
Hi,

This is a feature that will be added in next major release. For now, you can temporarily use the `dev` branch to get it - add this to `pubspec.yaml`:
```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: dev
```

Then you will need to obtain a `CalendarController` instance via `onCalendarCreated` callback; afterwards use `controller.nextPage()` and `controller.previousPage()`. Please note that `dev` branch does contain some breaking changes, so you might need to make some small adjustments in your project if you decide to use it.
