### ISSUE TITLE
The display for February is wrong.

### ISSUE THREAD

**Issue by motu2119** [aleksanderwozniak/table_calendar#451]
I'm using version 3.0.0-nullsafety.1. 
All other months are fine, but only February does not display the calendar correctly. 
What could be the cause?

<img width="297" alt="スクリーンショット 2021-03-30 21 09 40" src="https://user-images.githubusercontent.com/35750184/112987420-ab9cb900-919d-11eb-94de-5905c7308aec.png">

<img width="300" alt="スクリーンショット 2021-03-30 21 17 16" src="https://user-images.githubusercontent.com/35750184/112987444-b35c5d80-919d-11eb-83a4-7210c7292fde.png">

**Comment by aleksanderwozniak** [comment]
Hi, can you try using this in your pubspec.yaml instead?

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-nullsafety
```
