### ISSUE TITLE
Undefined class 'CalendarController'

### ISSUE THREAD

**Issue by riobijanero** [aleksanderwozniak/table_calendar#92]
I am importing the newest Version in Pubspec.yaml but when trying to declare a calender 
`CalendarController _calendarController; `
as in the example, I get an error:  Undefined class 'CalendarController'.

here is my Code:

`import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:table_calendar/table_calendar.dart';

class CalendarPage extends StatefulWidget {
  @override
  _CalendarPageState createState() => _CalendarPageState();
}

class _CalendarPageState extends State<CalendarPage> {
  CalendarController _calendarController;
  bool isLoading = false;
  List<AppointmentConcrete> freeAppointments = [];

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
        appBar: AppBar(
          title: Text(
              'Header Title'),
          centerTitle: true,
        ),
        body: ConstrainedBox(...);
  }
}
`

**Comment by aleksanderwozniak** [comment]
Can you show your `pubspec.yaml` file?

Check in `pubspec.lock` if **TableCalendar** has version `2.0.0`, like here:
```
table_calendar:
    dependency: "direct main"
    description:
      name: table_calendar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
```

**Comment by shriharip** [comment]
I am also facing this issue. I have the latest version 

My pubspec.lock is 
```
table_calendar:
    dependency: "direct main"
    description:
      name: table_calendar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
```
